{{- with (first .Values.spec.routing) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ include "bee.namespace" $ }}
spec:
  selector:
    app.kubernetes.io/name: {{ $.Release.Name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
